dist: xenial
language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install pytest-cov codecov

script:
  - pytest -v --cov

after_success:
  - codecov

deploy:
  provider: pypi
  user: coady
  password:
    secure: PP1AHv04EMNdBjfOdUKrWHivVNIZA2o6g3TJ8m4SRkz/0s6EXw26XkTd3YXdWe3aFMwvm2CjLaWxQvSA7UnNUG7SYNbcKeqDyl9ReZZCZi3BhOb8284boWLK4UV+mb5agJ/QQCClz1lXGDfiimfmGC7l8X7QBqyTJ54ZOTbM7/VwrT4m4NKHOCynXjVThEcTK6HoaKVUaKOoiVGpZ0TfAnonX0vGhI2bPbDyze9EsNrlVw1gj3PokZfIALThBgA2iAxD5+QVAUgDhl32LizMEZThNvWxPfQyKtB25rxqcjTon6mxzpv8p1uXT6/HUa+KLBKObM9DGKHYmvSixzjBwInQTO6rmB/hnGYSBI7Yyi7MM223jQsdiunDTa2XQ7axUi70FflUmBLnlrilANIxF5RZRf3GgeMt/dXh/VaQe24f+hYV3CDY3cZrejKTzoya5eOx6xlpVHkk/s5bHDtSiq7XEEQZ4IiZf7FHZvj4ucuYlfR8cqw61YUve3KCFHZTevcvg+mEZSxlmscUSrXasOsP2md9FKPWzE/zlADQkS0+4yl4yh9n0iiRD/hQQbnhaHxqlZa1jEs87zuZlYScBOFuRq2WKMN78ap5x9v64M/Kq09z0Tej/LSgHKlsDO75CAx1o8H5l2v0Bl3qyNwGSv3X/hf676xpqNcO5U4RJeM=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
